eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
	kafka:
		bootstrap-servers: localhost:9092
		topic:
			userCreated: USER_CREATED_TOPIC   


microservice:
  cart-service:
    endpoints:
      endpoint:
        uri: http://CART-SERVICE/cart/newItem
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
  customer-service:
    endpoints:
      endpoint:
        uri: http://CUSTOMER-SERVICE/
