eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  cart-service:
    endpoints:
      endpoint:
        uri: http://CART-SERVICE/cart/newItem
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
  customer-service:
    endpoints:
      endpoint:
        uri: http://CUSTOMER-SERVICE/customers/registerCustomer
